#Importing all the libraries


In [ ]:
import numpy as np
import matplotlib.pyplot  as plt
import pandas as pd
import seaborn as sns
import sklearn as sk

#Load the dataset

In [ ]:
data = pd.read_csv('/content/roses_LIBS_50000.csv')

In [ ]:
data.head(12)
# Element Peak Features (Ca, Mg, K, Na, etc.)
# Derived Ratios (Feature Engineering) Mg_over_Ca
# AUC Features (Area Under Curve) AUC_200_300
# Statistical Features  Std_Intensity, Centroid, FWHM
# Target Column Class

Ca_393.3    Ca_396.8    Ca_422.6    Mg_279.5    Mg_280.3    Mg_285.2  \
0   291.728395  342.596985  349.986864  379.325858  339.674962  349.426283   
1   324.612580  302.468884  365.863121  312.741746  318.900822  371.651960   
2   128.383183  129.636904  136.817224  131.532084  125.180148  117.458158   
3   393.723062  396.521411  432.069210  459.559584  474.287985  445.457964   
4    86.958634  105.978089  126.437587  183.639615  109.351935  145.198423   
5   227.795496  249.387321  291.255259  237.479137  233.824366  296.676577   
6    99.952800   96.728524  142.201014  153.143448  200.344504  144.854881   
7   311.669279  357.263857  313.625470  334.986687  375.953362  418.365390   
8   231.885292  162.810092  178.636956  217.049985  148.133616  227.939189   
9    63.722533  136.205367  179.936705  155.116288  170.014584  118.831606   
10  111.129142  136.352288   85.801474  130.987667  166.637559  153.522471   
11  249.605574  262.268799  283.390341  268.214398  306.816909  315.569512   

       K_766.5     K_769.9    Na_589.0    Na_589.6  ...  Std_Intensity  \
0   294.795641  353.984276  320.386757  319.032262  ...      27.305140   
1   395.200325  330.250116  329.776617  332.125169  ...      29.615951   
2   101.187247  119.379972   80.135018  139.546883  ...      24.647259   
3   440.579623  389.817143  328.470302  426.429379  ...      41.734125   
4   145.931144  142.294081  123.454394  132.659501  ...      26.441628   
5   306.003507  273.669470  274.748813  275.666321  ...      25.635527   
6   148.839453  112.685552  147.563058   76.692454  ...      32.848253   
7   405.397722  327.137863  304.403538  383.288825  ...      35.791884   
8   222.493342  190.668905  232.987549  168.894118  ...      26.327356   
9   161.635975  123.290500   10.857077   85.552820  ...      49.021691   
10  121.744453   79.038530   62.221392  149.750192  ...      35.621032   
11  337.357232  251.759511  269.228965  262.521707  ...      36.534857   

    Mg_over_Ca  K_over_Na  Fe_over_C  AUC_200_300  AUC_300_500  AUC_500_900  \
0     1.085455   1.014640   1.001776  1756.474430  1728.452665  1957.242279   
1     1.010423   1.096009   1.007671  1702.254871  1756.810712  2044.242573   
2     0.947657   1.004030   0.726226   657.443216   675.556441   626.836740   
3     1.128438   1.100009   0.866724  2308.848582  2063.189777  2342.881375   
4     1.372026   1.125379   0.922091   752.292443   631.283093   767.819199   
5     0.999404   1.053156   1.015208  1298.324601  1357.344514  1708.931030   
6     1.470548   1.166192   0.701272   764.020846   512.067057   701.027090   
7     1.149352   1.065208   1.010345  1862.485687  1756.278427  2090.923971   
8     1.034518   1.028069   0.942425   995.122389   959.488593  1168.232295   
9     1.168739   2.955365   1.404486   723.333685   652.571463   574.305006   
10    1.353648   0.947217   0.658973   729.364305   614.173826   632.524446   
11    1.119880   1.107882   0.950947  1462.757007  1465.762999  1602.010752   

      Centroid        FWHM    Class  
0   462.608351   82.309199  Class_4  
1   468.128733  100.437999  Class_4  
2   446.581654   51.413958  Class_1  
3   456.265816   63.476679  Class_5  
4   458.791570   55.452273  Class_1  
5   474.568855   50.530379  Class_3  
6   455.168982   95.171517  Class_1  
7   463.709957   72.622862  Class_4  
8   466.579857   82.984922  Class_2  
9   448.147079   95.924228  Class_1  
10  442.605983   93.433730  Class_1  
11  460.184572   94.015050  Class_3  

[12 rows x 29 columns]

In [ ]:
data.tail()

Ca_393.3    Ca_396.8    Ca_422.6    Mg_279.5    Mg_280.3    Mg_285.2  \
15946  251.751798  274.896886  232.736441  309.521180  284.825279  289.157973   
15947  124.461581  159.096010  137.176467  108.158551  201.254530  186.853207   
15948  312.416735  242.909327  298.496237  283.983341  264.440346  260.901277   
15949  174.758240  187.636973  216.303734  169.601652  194.248588  184.133258   
15950  124.951587  124.455176  101.789410  140.196014   69.796091  155.892445   

          K_766.5     K_769.9    Na_589.0    Na_589.6  ...  Std_Intensity  \
15946  277.958758  294.246787  238.730112  285.673320  ...      35.879473   
15947  193.172591   98.070883  118.862084   95.300466  ...      42.905540   
15948  285.535958  215.984953  272.293538  280.458705  ...      29.497995   
15949  196.212133  140.677501  153.116162  196.426844  ...      25.603944   
15950   85.757088   75.870334  137.437589  121.942769  ...            NaN   

       Mg_over_Ca  K_over_Na  Fe_over_C  AUC_200_300  AUC_300_500  \
15946    1.163447   1.091155   0.980483  1344.398865  1349.106943   
15947    1.179525   1.359918   0.819192   775.859906   666.796389   
15948    0.947885   0.907316   1.060254  1370.181571  1491.326429   
15949    0.946923   0.963800   0.831422   990.624686   978.005065   
15950         NaN        NaN        NaN          NaN          NaN   

       AUC_500_900    Centroid        FWHM    Class  
15946  1648.540732  471.310610  109.368498  Class_3  
15947   642.921247  444.824117  149.096539  Class_1  
15948  1541.355782  458.916773   65.628233  Class_3  
15949  1011.675484  453.700140   78.723221  Class_2  
15950          NaN         NaN         NaN      NaN  

[5 rows x 29 columns]

In [ ]:
data.shape     # 50000 rows and 29 features(columns)

(15951, 29)

In [ ]:
data.info()  # columns, types, missing data, and size.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15951 entries, 0 to 15950
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Ca_393.3        15951 non-null  float64
 1   Ca_396.8        15951 non-null  float64
 2   Ca_422.6        15951 non-null  float64
 3   Mg_279.5        15951 non-null  float64
 4   Mg_280.3        15951 non-null  float64
 5   Mg_285.2        15951 non-null  float64
 6   K_766.5         15951 non-null  float64
 7   K_769.9         15951 non-null  float64
 8   Na_589.0        15951 non-null  float64
 9   Na_589.6        15951 non-null  float64
 10  Fe_248.3        15951 non-null  float64
 11  Fe_373.5        15951 non-null  float64
 12  Fe_404.5        15951 non-null  float64
 13  C_247.8         15951 non-null  float64
 14  H_656.3         15950 non-null  float64
 15  O_777.0         15950 non-null  float64
 16  Peak_Intensity  15950 non-null  float64
 17  Max_Intensity   15950 non-null 

In [ ]:
data.isnull().sum()   # False = 0

Ca_393.3          0
Ca_396.8          0
Ca_422.6          0
Mg_279.5          0
Mg_280.3          0
Mg_285.2          0
K_766.5           0
K_769.9           0
Na_589.0          0
Na_589.6          0
Fe_248.3          0
Fe_373.5          0
Fe_404.5          0
C_247.8           0
H_656.3           1
O_777.0           1
Peak_Intensity    1
Max_Intensity     1
Mean_Intensity    1
Std_Intensity     1
Mg_over_Ca        1
K_over_Na         1
Fe_over_C         1
AUC_200_300       1
AUC_300_500       1
AUC_500_900       1
Centroid          1
FWHM              1
Class             1
dtype: int64

In [ ]:
data.describe()


Ca_393.3      Ca_396.8      Ca_422.6      Mg_279.5      Mg_280.3  \
count  15951.000000  15951.000000  15951.000000  15951.000000  15951.000000   
mean     250.669755    258.742244    266.378123    273.983125    282.663602   
std      109.622922    109.558609    109.810481    109.406649    109.926669   
min        0.400040     10.846658     16.139250     21.201589      1.189584   
25%      158.218288    166.334326    174.338432    181.131033    190.189259   
50%      252.597713    258.252871    266.740579    274.362065    282.583419   
75%      341.933850    350.617217    357.970571    366.299365    374.339515   
max      505.860493    513.343203    522.312587    527.544249    567.073668   

           Mg_285.2       K_766.5       K_769.9      Na_589.0      Na_589.6  \
count  15951.000000  15951.000000  15951.000000  15951.000000  15951.000000   
mean     290.385360    298.027182    250.348715    258.064885    266.328120   
std      109.568565    109.770190    109.426584    109.261125    109.826925   
min       23.265026     38.879410      0.151533      1.723502     24.519992   
25%      197.829125    205.975970    158.553369    166.850896    174.145315   
50%      291.550511    299.080687    251.556378    258.861241    267.602643   
75%      381.274470    389.552348    341.734716    348.869195    357.926104   
max      546.572498    543.029459    504.493985    509.279683    515.578496   

       ...  Mean_Intensity  Std_Intensity    Mg_over_Ca     K_over_Na  \
count  ...    15950.000000   15950.000000  15950.000000  15950.000000   
mean   ...      271.783526      33.903085      1.124906      1.069886   
std    ...      105.711119       6.045756      0.169884      0.179416   
min    ...       94.729958      12.433601      0.607517      0.410882   
25%    ...      192.058171      29.746859      1.027059      0.969752   
50%    ...      272.270680      33.748179      1.091596      1.044891   
75%    ...      351.676672      37.873232      1.178400      1.136584   
max    ...      451.617430      57.613377      2.884417      3.451792   

          Fe_over_C   AUC_200_300   AUC_300_500   AUC_500_900      Centroid  \
count  15950.000000  15950.000000  15950.000000  15950.000000  15950.000000   
mean       0.953632   1419.634978   1347.954715   1580.946722    461.670114   
std        0.149497    531.452716    531.525754    636.892247      7.571574   
min        0.440929    453.535086    384.998671    408.884809    412.636090   
25%        0.869689   1003.564843    929.194088   1084.428333    458.426561   
50%        0.946347   1421.935863   1351.871824   1586.633387    462.681737   
75%        1.024377   1834.988392   1763.972524   2079.325285    466.199215   
max        2.538791   2385.681027   2330.368024   2769.173857    498.513653   

               FWHM  
count  15950.000000  
mean      84.589895  
std       24.899914  
min       22.134284  
25%       65.250348  
50%       82.000850  
75%      101.465821  
max      184.005821  

[8 rows x 28 columns]

In [ ]:
data.dropna(inplace=True)
X = data.drop("Class", axis=1)   # all numeric LIBS features
y = data["Class"]                # rose species label

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train[:5]

Ca_393.3    Ca_396.8    Ca_422.6    Mg_279.5    Mg_280.3    Mg_285.2  \
11735  358.947543  442.129397  419.048152  436.915938  430.006731  426.901453   
578    417.917161  411.345185  392.996579  458.106228  460.425874  435.027936   
5265   119.040800  148.969841  107.895085   94.652225  162.903940  130.625674   
4995   129.994279  251.158988  158.855800  241.862389  145.783035  205.464951   
9758   212.163148  156.963052  164.528508  198.269634  261.347432  207.426917   

          K_766.5     K_769.9    Na_589.0    Na_589.6  ...  Mean_Intensity  \
11735  421.082095  391.149649  387.237262  405.916372  ...      420.786520   
578    424.179573  381.462701  407.881401  385.773582  ...      421.519650   
5265   118.941428   50.623345  106.979910  123.466338  ...      127.707962   
4995   162.961579  146.147003  172.191235  207.909036  ...      182.354853   
9758   237.316307  163.503192  171.978813  182.902521  ...      194.084922   

       Std_Intensity  Mg_over_Ca  K_over_Na  Fe_over_C  AUC_200_300  \
11735      27.433818    1.060403   1.024053   1.066177  2178.301782   
578        25.787819    1.107425   1.015104   0.982096  2203.018444   
5265       40.708421    1.032657   0.735811   0.884786   717.582186   
4995       41.794450    1.098334   0.813229   0.704293   970.900238   
9758       34.072027    1.249954   1.129447   0.963067  1083.739966   

       AUC_300_500  AUC_500_900    Centroid        FWHM  
11735  2117.471946  2436.810590  462.146922   64.736743  
578    2111.410918  2429.885037  461.673863   63.225775  
5265    736.414770   589.330443  435.396420   99.086649  
4995    931.569808  1015.207602  455.559203  115.162135  
9758    943.235844  1078.382937  453.563017   65.004637  

[5 rows x 28 columns]

In [ ]:
X_train.shape

(12760, 28)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.impute import SimpleImputer

# Impute missing values in X_test (before scaling)
imputer = SimpleImputer(strategy='mean')
X_test_imputed = imputer.fit_transform(X_test)

# Re-apply StandardScaler to the imputed X_test
X_test = scaler.transform(X_test_imputed)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
from sklearn.svm import SVC
model = SVC(kernel='rbf', C=10, gamma='scale')
model.fit(X_train, y_train)

SVC(C=10)

In [ ]:
y_pred = model.predict(X_test)


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.2006269592476489

Classification Report:
               precision    recall  f1-score   support

     Class_1       0.20      1.00      0.33       640
     Class_2       0.00      0.00      0.00       617
     Class_3       0.00      0.00      0.00       688
     Class_4       0.00      0.00      0.00       643
     Class_5       0.00      0.00      0.00       602

    accuracy                           0.20      3190
   macro avg       0.04      0.20      0.07      3190
weighted avg       0.04      0.20      0.07      3190


Confusion Matrix:
 [[640   0   0   0   0]
 [617   0   0   0   0]
 [688   0   0   0   0]
 [643   0   0   0   0]
 [602   0   0   0   0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
